Prueba_Tecnica_CRUD_J/Models/ErrorViewModel.cs
namespace Prueba_Tecnica_CRUD_J.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Prueba_Tecnica_CRUD_J/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Prueba_Tecnica_CRUD_J.Models;
using System.Diagnostics;

namespace Prueba_Tecnica_CRUD_J.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Prueba_Tecnica_CRUD_J/Controllers/PersonaJController.cs
using Prueba_Tecnica_CRUD_J.BL;
using Prueba_Tecnica_CRUD_J.EN;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Prueba_Tecnica_CRUD_J.Controllers
{
    public class PersonaJController : Controller
    {
        // GET: PersonaJController
        public async Task<ActionResult> Index()
        {
            var perj = await PersonaJBL.GetAll();
            return View(perj);
        }

        // GET: PersonaJController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var use = await PersonaJBL.GetById(id);
            return View(use);
        }

        // GET: PersonaJController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PersonaJController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PersonaJ personaj)
        {
            try
            {
                var perj = await PersonaJBL.Create(personaj);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PersonaJController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var perj = await PersonaJBL.GetById(id);
            return View(perj);
        }

        // POST: PersonaJController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PersonaJ personaj)
        {
            try
            {
                var perj = await PersonaJBL.Update(personaj);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PersonaJController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var perj = await PersonaJBL.GetById(id);
            return View(perj);
        }

        // POST: PersonaJController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(PersonaJ personaj)
        {
            try
            {
                var perj = await PersonaJBL.Delete(personaj);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Prueba_Tecnica_CRUD_J/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Prueba_Tecnica_CRUD_J/Views/PersonaJ/Create.cshtml
@model Prueba_Tecnica_CRUD_J.EN.PersonaJ

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PersonaJ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreJ" class="control-label"></label>
                <input asp-for="NombreJ" class="form-control" />
                <span asp-validation-for="NombreJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoJ" class="control-label"></label>
                <input asp-for="ApellidoJ" class="form-control" />
                <span asp-validation-for="ApellidoJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SueldoJ" class="control-label"></label>
                <input asp-for="SueldoJ" class="form-control" />
                <span asp-validation-for="SueldoJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstatusJ" class="control-label"></label>
                <input asp-for="EstatusJ" class="form-control" />
                <span asp-validation-for="EstatusJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" class="form-control" />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComentariosJ" class="control-label"></label>
                <input asp-for="ComentariosJ" class="form-control" />
                <span asp-validation-for="ComentariosJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Prueba_Tecnica_CRUD_J/Views/PersonaJ/Delete.cshtml
@model Prueba_Tecnica_CRUD_J.EN.PersonaJ

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonaJ</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SueldoJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SueldoJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstatusJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstatusJ)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeNacimiento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaDeNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComentariosJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComentariosJ)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Prueba_Tecnica_CRUD_J/Views/PersonaJ/Details.cshtml
@model Prueba_Tecnica_CRUD_J.EN.PersonaJ

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PersonaJ</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SueldoJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SueldoJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstatusJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstatusJ)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDeNacimiento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaDeNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComentariosJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComentariosJ)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Prueba_Tecnica_CRUD_J/Views/PersonaJ/Edit.cshtml
@model Prueba_Tecnica_CRUD_J.EN.PersonaJ

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PersonaJ</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreJ" class="control-label"></label>
                <input asp-for="NombreJ" class="form-control" />
                <span asp-validation-for="NombreJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoJ" class="control-label"></label>
                <input asp-for="ApellidoJ" class="form-control" />
                <span asp-validation-for="ApellidoJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SueldoJ" class="control-label"></label>
                <input asp-for="SueldoJ" class="form-control" />
                <span asp-validation-for="SueldoJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstatusJ" class="control-label"></label>
                <input asp-for="EstatusJ" class="form-control" />
                <span asp-validation-for="EstatusJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDeNacimiento" class="control-label"></label>
                <input asp-for="FechaDeNacimiento" class="form-control" />
                <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComentariosJ" class="control-label"></label>
                <input asp-for="ComentariosJ" class="form-control" />
                <span asp-validation-for="ComentariosJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Prueba_Tecnica_CRUD_J/Views/PersonaJ/Index.cshtml
@model IEnumerable<Prueba_Tecnica_CRUD_J.EN.PersonaJ>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
          @*   <th>
                @Html.DisplayNameFor(model => model.Id)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.NombreJ)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoJ)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SueldoJ)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstatusJ)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ComentariosJ)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreJ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoJ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SueldoJ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstatusJ)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaDeNacimiento)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.ComentariosJ)
            </td>
            <td>
                    <a href="@Url.Action("Edit", new{Id = item.Id})" class="btn btn-success"><i class="fas fa-edit"></i></a>
                    <a href="@Url.Action("Details", new{Id = item.Id})" class="btn btn-info"><i class="fas fa-eye"></i></a>
                    <a href="@Url.Action("Delete", new{Id = item.Id})" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

Prueba_Tecnica_CRUD_J/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prueba_Tecnica_CRUD_J</title>
    <script src="~/starboostrap/fontawesome.min.js"></script>
    <link href="~/starboostrap/css/styles.css" rel="stylesheet" />

</head>
<body class="sb-nav-fixed">  
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Ivote-System</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" asp-action="Logout" asp-controller="User">Salir</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" asp-action="Index" asp-controller="Home">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Inicio
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            
                            
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Configuration
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" asp-action="Index" asp-controller="PersonaJ">PersonasJ</a>
                                       
                                    </nav>
                                </div>


                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Ivote-System
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        @RenderBody()
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <main>
            <div class="container-fluid px-4">
                @RenderBody()
            </div>
        </main>   
    <script src="~/starboostrap/js/scripts.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>